farao-community/gridcapa-swe

pom.xml
=> upgrade farao-dpendencies

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweRequest.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweRequestTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileImporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/SweRunner.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/NetworkImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java
=> import crac with network in runnner

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweRequest.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweRequestTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileImporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/NetworkService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/SweRunner.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/NetworkImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml
=> Handle boundary files

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileImporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/SweRunner.java, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_FR-ES.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_PT-ES.json, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/NetworkImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java
=> add sperate import crac for es-pt and fr-es borders

gridcapa-swe-runner-app/src/main/resources/application.yml
=> add minio to whitelist for swe runner

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileImporter.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java
=> build correction

gridcapa-swe-runner-app/pom.xml, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/voltage/VoltageResultMapper.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/voltage/json/VoltageCheckConstraintElement.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/voltage/json/VoltageCheckResult.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/voltage/VoltageMonitoringResultTestUtils.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/voltage/VoltageResultMapperTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/voltage/json/VoltageCheckConstraintElementTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/voltage/json/VoltageCheckResultTest.java, pom.xml
=> add json voltage check export

pom.xml
=> update farao dependencies version to v1.6.2

gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_FR-ES.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_PT-ES.json
It adds timeseries taken into account during the crac import
=> add timeseries for fr-es crac and pt-es crac

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweResponse.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweResponseTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelization.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResult.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/ExecutionResult.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/ParallelExecution.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/OutputService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/RequestService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocument.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelizationTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/parallelization/ParallelExecutionTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/OutputServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocumentTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/voltage/VoltageMonitoringResultTestUtils.java, gridcapa-swe-runner-app/src/test/resources/network/network.xiidm
=> adding voltage check calculation and final export as zip file

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocument.java
Change the value in the ddoc doc to an integer to remove the decimal part
=> change ttc value to integer

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweResponse.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweResponseTest.java, gridcapa-swe-runner-app/pom.xml, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelization.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweData.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResult.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileImporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FilesService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/RequestService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelizationTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDataTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResultTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CneFileExportServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FilesServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/OutputServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocumentTest.java, pom.xml
=> generate CNE files for swe

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/ProcessConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/OutputService.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/OutputServiceTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml
=> export swe files with names in local date-time

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/ParallelExecution.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/SweForkJoinWorkerThreadFactory.java
=> fixes missing jaxb library bug when multithreading in docker

pom.xml
=> farao-dependencies : 1.7.0 -> 1.7.1

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweData.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDataTest.java
=> correction of swe data constructor

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyDirection.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLogging.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelization.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunner.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/DichotomyParallelizationWorker.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocument.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyDirectionTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunnerTest.java, pom.xml
=> Addinf dichotomy direction to events

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweResponse.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweResponseTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelization.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/RequestService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelizationTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java
=> remove useless fields in swe response

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java
=> Increase number of iteration of balancing adjustment

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/ProcessConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelization.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/NetworkShifterProvider.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifterTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml
=> Make maximum number of iteration for balances adjustment configurable

gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java
=> change test

pom.xml
=> [SWE] Upgrade dependencies

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunner.java, pom.xml
=> farao-dichotomy : 4.9.0 -> 4.9.1

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunner.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweData.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FilesService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunnerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidatorTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDataTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java
=> separate raoParameters file for each border

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, pom.xml
farao-core: 1.11.0 -> 1.12.0
farao-dichotomy: 4.9.1 -> 4.10.0
=> upgrade version:

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifterTest.java
=> swe use glsk as default for pmin pmax on generators

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/ZonalScalableProvider.java, pom.xml
=> Upgrade gridcapa-rao-runner and farao-dependencies to version 1.13.0

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifterTest.java
Reverts farao-community/gridcapa-swe#106
=> Revert "Fix shift balancing adjustment"

gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyResultHelperTest.java, gridcapa-swe-runner-app/src/test/resources/dichotomy/RaoResult.json, pom.xml
=> Upgrade farao dependencies

Dockerfile, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, pom.xml
=> Add the ScalingParameter "reconnect" and upgrade farao-dichotomy to 4.11.0

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocument.java
=> set ttc value to 0 instead of nothing when there is an error

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocument.java
=> add indentation in ttcdoc file

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java
=> add p tolerance

.github/workflows/ci-commit.yml, .github/workflows/ci-main.yml, .github/workflows/release.yml, Dockerfile, pom.xml
=> Migrate to java 17

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLogging.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/OutputService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/voltage/json/FailureVoltageCheckResult.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLoggingTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/OutputServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckServiceTest.java
=> Fix voltage check network usage and make resilient to exceptions

.github/workflows/release.yml
=> Update release workflow for hotfixes

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java
=> add business logs for loadflow divergence and no valid step for voltage check

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyValidationDataTest.java, pom.xml
=> Adapt rao request to builder pattern

.github/workflows/ci-main.yml
=> remove broadcast event from workflow ci-main

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java, gridcapa-swe-runner-app/src/test/resources/export_cgmes/TestCase_with_swe_countries.xiidm, pom.xml
No
Bug fix 
Errors on cgmes files due to inconsistencies between SSH and EQ files. 
Missing elements in SV/SSH files
The full export strategy and the upgrade of powsybl version fix the problems of exported cgm files
**Does this PR introduce a breaking change?** *(What changes might users need to …
=> Using full export for EQ,TP, SSH

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java
=> fix cgmes export

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLogging.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLoggingTest.java
=> Add TS to BD summary logs

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CneFileExportServiceTest.java
=> For base case unsecure do not output last secure error file

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/configuration/ProcessConfiguration.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/configuration/ProcessConfigurationTest.java, gridcapa-swe-commons/src/test/resources/application.yml, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/resources/application.yml
=> Export valid cgm modeling authority

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/NetworkService.java
=> Change pst handling to set regulating false

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java
=> Add anglemonitoring result to raoResult

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/hvdc/HvdcLinkProcessor.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/hvdc/HvdcLinkProcessorTest.java, gridcapa-swe-commons/src/test/resources/hvdc/SwePreprocessorParameters_no_angle_droop.json, gridcapa-swe-commons/src/test/resources/hvdc/TestCase16Nodes_no_angle_droop_afterModif.xiidm
=> Should not reconnect line if angle droop power is disabled

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckServiceTest.java
=> Add voltage check logs in case of constraints

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java
=> add name and degree of the angle in constraint when there is an unsecure angle check in business log

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLogging.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLoggingTest.java
=> dispaly int value for current ttc and previous ttc

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/PstConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/NetworkService.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/configurations/PstConfigurationTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml
=> avoid hard coded pst ids 

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java, gridcapa-swe-runner-app/src/test/resources/export_cgmes/TestCase_with_swe_countries.xiidm
=> Use model version for ssh version file name

gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_FR-ES_D2CC.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_FR-ES_IDCC.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_PT-ES_D2CC.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_PT-ES_IDCC.json, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java, pom.xml
Upgrade to powsybl core 6.2.3
Upgrade to powsybl open rao 5.2.0 (add parameters to cimCracCreation)
Upgrade to powsybl entsoe 2.8.1
(if any of the …
=> Upgrapde farao-dependencies

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/UnoptimizedCnecsPstConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/configurations/UnoptimizedCnecsPstConfigurationTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml
=> Add configuration for unoptimized cnecs with pst

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckServiceTest.java
=> improve logs msg in case of unsecure voltage check

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweTaskParameters.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FilesService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunnerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweTaskParametersTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java
=> Second preventive parameter

gridcapa-swe-commons/pom.xml, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/diff_shift/DiffShiftedGenerator.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/diff_shift/DiffShiftedNetworkTest.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/diff_shift/GeneratorInformation.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/diff_shift/ScalableInformation.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/shift/DiffShiftedNetworkTest.java, gridcapa-swe-commons/src/test/resources/shift/TestCase_with_transformers_shift_es_fr_1000.xiidm
=> Add test to display difference on network during shift

pom.xml
=> Upgrade farao dependencies to 1.27.0

pom.xml
=> Upgrade rao runner and dichotomy

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/resource/ProcessType.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/resource/ProcessTypeTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/NetworkShifterProvider.java
=> Add btcc process configuration to swe runner

gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_FR-ES_D2CC.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_FR-ES_IDCC.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_PT-ES_D2CC.json, gridcapa-swe-runner-app/src/main/resources/crac/CimCracCreationParameters_PT-ES_IDCC.json, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java
=> put max-ra-per-tso for RTE to 3

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/exception/SweBaseCaseUnsecureException.java, gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/CountryBalanceComputation.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/exception/SweBaseCaseUnsecureExceptionTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/NetworkShifterProvider.java
=> Add secure / unsecure initial loadflow logging

pom.xml
=> Upgrade to OLF 1.8.2

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java, pom.xml
=> Fix SV metadata export 

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/PstConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/NetworkService.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/configurations/PstConfigurationTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/NetworkServiceTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml, gridcapa-swe-runner-app/src/test/resources/hvdc/TestCase16Nodes.xiidm
=> Update config for PST regulation

pom.xml
=> upgrade farao dependecies

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileExporterTest.java
=> Zip Cgm files inside CGM zip

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/resource/SweEICode.java, gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/CountryBalanceComputation.java, gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweD2ccShiftDispatcher.java, gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweIdccShiftDispatcher.java, gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweNetworkShifter.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/diff_shift/DiffShiftedNetworkTest.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweD2ccShiftDispatcherTest.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweIdccShiftDispatcherTest.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweNetworkShifterTest.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/shift/ZonalScalableProviderTest.java, gridcapa-swe-commons/src/test/resources/com/powsybl/config/test/config.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/NetworkShifterProviderTest.java
=> Update Glsk limitation strategy

pom.xml
=> upgrade farao dependencies to 1.32.0

gridcapa-swe-runner-app/src/main/resources/application.yml
=> Harmonize application.yml

gridcapa-swe-runner-app/src/main/resources/logback.xml
=> Update logback file in order dispaly RaoBusinessWarns and RaoBusinessLogs

pom.xml
=> upgrade swe to olf 1.11.1

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileImporter.java
=> Add logs and Improve old logs message when importing files

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweResponse.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/RequestService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/RequestServiceTest.java
=> Delete response sent after computing swe request

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/resource/ProcessType.java, gridcapa-swe-commons/src/test/java/com/farao_community/farao/gridcapa_swe_commons/resource/ProcessTypeTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java
=> fix Shifted CGM naming convention for SWE DACF

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweRequest.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweRequestTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/SweApplication.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/UrlConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweData.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FilesService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/SweRunner.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/utils/UrlValidationService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDataTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FileImporterTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FilesServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/NetworkServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/RequestServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java, gridcapa-swe-runner-app/src/test/resources/application.yml, pom.xml
=> Add interrupt pending

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CgmesExportServiceTest.java
=> Delete the use of absolute value and cap to 00 if negative

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/GeneratorLimitsHandler.java
=> change some access modifiers to public for common usage with swe-csa

gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/ScalableGeneratorConnector.java, gridcapa-swe-commons/src/main/java/com/farao_community/farao/gridcapa_swe_commons/shift/SweNetworkShifter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CneFileExportServiceTest.java, pom.xml
:warning: Requires the PR https://github.com/farao-community/farao-dichotomy/pull/72 to be merged and released
(if any of the questions/checkboxes …
=>  Update of Reason and Error code in the CNE first_unsecure

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/SweApplication.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/configurations/NetworkExportConfiguration.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FilesService.java, gridcapa-swe-runner-app/src/main/resources/application.yml, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/FilesServiceTest.java
=> Export iidm before dichotomy

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java
=> Fix GLSK import in Angle check

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java
=> Use step-related rao-result instead of previous-step-related rao-result in angle check

pom.xml
=> Upgrade versions to use OLF 1.22.2

gridcapa-swe-runner-api/src/main/java/com/farao_community/farao/swe/runner/api/resource/SweResponse.java, gridcapa-swe-runner-api/src/test/java/com/farao_community/farao/swe/runner/api/resource/SweResponseTest.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelization.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidator.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResult.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyValidationData.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/DichotomyParallelizationWorker.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/RequestService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/SweRunner.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/ttc_doc/TtcDocument.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelizationTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyRunnerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/RaoValidatorTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResultTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyValidationDataTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/parallelization/DichotomyParallelizationWorkerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/RequestServiceTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/SweRunnerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/VoltageCheckServiceTest.java, pom.xml
=> Interrupt computation after rao failure

pom.xml
=> upgrade farao dependencies to v1.34.3 and farao-dichotomy to v1.21.1

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLogging.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyLoggingTest.java
=> fix the limiting element reported in summary logs

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResult.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/DichotomyParallelizationWorker.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CneFileExportService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/dichotomy/DichotomyParallelizationTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/domain/SweDichotomyResultTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/CneFileExportServiceTest.java, pom.xml
=> Fix CNE First Unsecure + Upgrade Powsybl core & OLF

gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/NetworkServiceTest.java
Add a test to verify that the following issue has been correctly fixed on Powsybl side : 
https://github.com/powsybl/powsybl-core/issues/3295
Awaiting new release of Powsybl in March 2025.
**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due …
=> Check that boundaries are correctly imported in CgmesMetadataModels Extension

gridcapa-swe-runner-app/pom.xml, gridcapa-swe-runner-starter/pom.xml
=> Add Maven configuration to enable inline mocking

gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/parallelization/DichotomyParallelizationWorker.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/FileExporter.java, gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/OutputService.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/parallelization/DichotomyParallelizationWorkerTest.java, gridcapa-swe-runner-app/src/test/java/com/farao_community/farao/swe/runner/app/services/OutputServiceTest.java
=> [SER] Export raoresult and networkwithpra
